### DISCUSSION TITLE
Setting BGP display format to asdot notation

### DISCUSSION THREAD

**Discussion by rich9474** [aristanetworks/avd#2213] [Q&A] [answered]
I don't see any reference in the Docs to setting the display format on the devices to use asdot notation other than Fix #1164 referencing asdot trailing 0's, but no way to set it as the display preference.

Issue #1832 discussed the functionality, but it looks like it ran out of steam and was auto closed.  

Currently I am just setting on the group_vars/DC1_L3Leafs.yml:
```
l3leaf:
  defaults:
    bgp_defaults:
      - 'bgp as notation asdot'
```
I can't work out how to set it at the Fabric level, which would be better and save duplication.  It would be nice to get this as a settable option in eos_design.
