### DISCUSSION TITLE
l3_edge configuration

### DISCUSSION THREAD

**Discussion by rich9474** [aristanetworks/avd#2215] [Q&A] [answered]
Hi am attempting to configure a multi DC Fabric, and am struggling to work out how the DCI & L3 Edge configuration is supposed to work.  I would like to be able to stretch L2 vlans across DCs for VM migration.  the l3_edge config is fairly simple, but I am not sure how it is supposed to work both from the perpective of connecting the overlay VRF to external devices such as firewalls, and also for the inter site DCI connections.  

The docs say "Make sure to configure the variables in a group_vars file covering all devices mentioned in the data model." but I can't see how I shoild reference the DCI configured under the L3_edge.

I have the following config 
```
l3_edge:
  p2p_links_ip_pools:
    ip_pool_wan: "10.10.250.0/24"
  p2p_links_profiles:
    p2p_defaults:
      ip_pool: ip_pool_wan
      include_in_underlay_protocol: true
      bfd: true
      ptp_enable: true

  p2p_links:
    # Inter DC connections
    - id: 1
      profile: p2p_defaults
      nodes: [ dc1-wan1a, dc2-wan1a ]
      interfaces: [ Ethernet55/1, Ethernet55/1 ]
      as: [ "65001.1", "65002.1" ]
    - id: 2
      profile: p2p_defaults
      nodes: [ loynwan1b, losnwan1b ]
      interfaces: [ Ethernet55/1, Ethernet55/1 ]
      as: [ "65001.1", "65002.1" ]
    # Old world connections
    - id: 3
      profile: p2p_defaults
      nodes: [ l"dc1-wan1a", "dc1-core1" ]
      interfaces: [ Ethernet5, Ethernet1/45 ]
      as: [ "65001.1", "64999" ]
      speed: 10g
      include_in_underlay_protocol: false   # not sure about this
    - id: 4
      profile: p2p_defaults
      nodes: [ "dc1-wan1b", "dc1-core2" ]
      interfaces: [ Ethernet5, Ethernet1/45 ]
      as: [ "65001.1", "64999" ]
      speed: 10g
      include_in_underlay_protocol: false   # not sure about this
```

setting `include_in_underlay_protocol: true` seems to add config for the underlay bgp routing peering, but having false does not include the link in the Overlay peering config., it just sets an IP on the interface in the default vlan

Can someone please either point me in the direction of a multi DC example using l3_edge or explain what other components are required.
