### DISCUSSION TITLE
How to replace keys with new AVD4.0 append_rp behaviour

### DISCUSSION THREAD

**Discussion by kmueller68** [aristanetworks/avd#2565] [Q&A]
Hello.

The merge behaviour for custom_structured_configuration hase been changed starting with AVD 4.0 to from ```replace``` to  ```append_rp```.
```
# From AVD 4.0 most data models will use lists instead of dicts.
# Input data is auto-converted from dicts to lists so it is more likely that "custom_structured_configuration_list_merge: replace" will overwrite list data unintentionally.
# So "replace" should be avoided for most use cases going forward.
# "append_rp" means "append unique items", so similar to append, but avoid duplicates in the resulting list.
custom_structured_configuration_list_merge: 'append_rp'
```

Could you please give me a hint how to handle the follwing requirement with ```append_rp```:

we set the follwing in ```all.yml```:
```
management_ssh:
  idle_timeout: 30
  enable: false
  vrfs:
    MGMT:
      enable: true
  ```
  but in a more specific group_vars file we need to replace it with:
  ```
  management_ssh:
    idle_timeout: 30
    enable: false
    vrfs:
      VLAN1810:
        enable: true
  ```
  
 With the AVD 4.0 behaviour I get:
 ```
management_ssh:
  idle_timeout: 30
  enable: false
  vrfs:
    MGMT:
      enable: true
    VLAN1810:
      enable: true
 ```

Thank you very much for your help.
