### DISCUSSION TITLE
Campus L3LS evpn - how to add lldp ztp-vlan config to l3leafs to interfaces connected to l2leafs?

### DISCUSSION THREAD

**Discussion by kmueller68** [aristanetworks/avd#2608] [Q&A] [answered]
Hello.

I am using ```eos_designs``` to render a L3LS evpn fabric with spines, l3leafs and l2leafs for a campus setup.
The l2leafs (campus access) should be able to run ZTP via the campus ZTP feature based on ```lldp ztp vlan```.
Therefore I have to add  
```
lldp:
  ztp_vlan: 1810
```
to each interface on the L3leafs to which a L2leaf will be connected to.

I currently do it by using ```network_ports:```
```
### Add ZTP LLDP TLV to downlinks to access switches
network_ports:
 - switches:
    - distri-10-0[1-2].LAN.MU
   switch_ports:
     - Ethernet1-20
   structured_config:
     lldp:
       ztp_vlan: 1810
```
but with this the individual interface description set by ```eos_designs``` will be deleted.
```
interface Ethernet2
   description 
   no shutdown
   channel-group 2 mode active
   lldp ztp vlan 1810
```
instead of
```
interface Ethernet2
   description ACCESS-10-021-01.LAN.MU_Ethernet99
   no shutdown
   channel-group 2 mode active
```

Could you please help me finding a solution to add the ```lldp ztp vlan``` configuraiton without loosing the interfaces description?

Thank you
Karlheinz

**Comment by ClausHolbechArista** [comment]
A quickfix would be to use structured_config for uplinks.
I suppose the l2leaf is already configured in AVD inventory. So if you set:
```
l2leaf:
  defaults:
    uplink_structured_config:
      lldp:
        ztp_vlan: 1810
```
Only caveat is that it will configure the command in both ends, so the l2leaf will also have this configured on the uplink port-channel, but since the schema does not allow this key, it will give a warning at runtime.

To avoid this issue we would have to implement a proper feature for this. It could be something like `downlink_ztp_vlan` defined on the `l3leaf` or `uplink_ztp_vlan` defined on the `l2leaf`?

**Comment by kmueller68** [comment]
Thank you for your answer.
The quickfix is  unfortunately not meeting the requirement.
```
l2leaf:
  defaults:
    uplink_structured_config:
      lldp:
        ztp_vlan: 1810
 ```
 This will put ```lldp ztp_vlan```under the final port-channel interface to which the l2leaf will be connected at the final end.
 ```
 - description: ACCESS-10-011-01.LAN.MU_Po99
  type: switched
  shutdown: false
  mode: trunk
  vlans: 502,507,512,517,522,527,532,537,542,557,562,567,572,577,582,597,1810,2210,2510,3400-3404
  mlag: 1
  name: Port-Channel1
  lldp:
    ztp_vlan: 1810
 ```
But lldp is not supported on cli under port-channel interfaces and for campus ztp the ```lldp tlv transmit ztp vlan 1810``` has to be configured on the ethernet interfaces.
 https://www.arista.com/en/support/toi/eos-4-27-1f/14879-campus-ztp-through-vlan-advertised-from-spine-aggregation-switch
 
 Do you have any other idea on this?

**Reply by ClausHolbechArista** [reply]
Sorry I didn't think about that.
We need to rewrite the uplink_structured_configuration, so this is just another reason to do so. We do not have a knob to get the config under the physical interfaces.

**Comment by kmueller68** [comment, marked as answer]
I successfully tested one workaround based on your hints.
I add the raw cli config for each campus l3leaf/distri pair.  
```
    MU_LAN_DISTRI_10:
      bgp_as: 65410
      inband_management_subnet: 10.100.10.00/24
      inband_management_vlan: 1810
      filter:
        tenants: [all]
        tags: [b10, inet]
      raw_eos_cli: |
        interface ethernet1-20
          lldp tlv transmit ztp vlan 1810
      nodes:
        distri-10-01.LAN.MU:
          id: 7
          mgmt_ip: 172.21.234.17
          uplink_switch_interfaces: ['Ethernet5', 'Ethernet5']
        distri-10-02.LAN.MU:
          id: 8
          mgmt_ip: 172.21.234.18
          uplink_switch_interfaces: ['Ethernet6', 'Ethernet6']
```
will provide the following line at the final cli for the l3leaf switches:
```
interface ethernet1-20
  lldp tlv transmit ztp vlan 1810
```
