### DISCUSSION TITLE
How to configure BGP peer groups to right nodes in network services?

### DISCUSSION THREAD

**Discussion by rradim** [aristanetworks/avd#2902] [Q&A] [answered]
Hi all,

I'm wondering how to correctly use BGP peer groups in network services...(not speaking about underlay/overlay etc bgp groups) in AVD documentation it says:

```

    # Dictionary of BGP peer groups definitions | Optional.
    # This will configure BGP peer groups to be used inside the tenant for peering with external devices.
    # Since BGP peer groups are configured at higher BGP level, shared between VRFs,
    # peer_group names should not overlap between VRFs.
    bgp_peer_groups:
      - name: < BGP peer group name >
        remote_as: < bgp_as >
        description: "< description as string >"
        send_community: < standard | extended | large | all >
        next_hop_self: < true | false >
        maximum_routes: < 0-4294967294 >
        default_originate:
          enabled: < true | false >
          always: < true | false >
        # Nodes is required to restrict configuration of BGP peer groups to certain nodes in the network.
        # If not set the peer-group is created on the device which has a bgp_peer mapped to corresponding peer_group.
        nodes: [ < node_1 >, < node_2 > ]
        update_source: < interface >
        bfd: < true | false >
        ebgp_multihop: < 1-255 >
        route_map_out: < route-map name >
        route_map_in: < route-map name >
        local_as: < local BGP ASN >         
```

My question targets this comment: 
 `# If not set the peer-group is created on the device which has a bgp_peer mapped to corresponding peer_group.`

Please can anyone give me a hint how to properly set a peer group in a way, that AVD recognizes it and configures the peer group to the node?

Only way I found is to use hosts_vars.yml & `custom_structured_configuration_router_bgp:` - which means `eos_design` module does not know about it..right?

Thanks
Radim
