### DISCUSSION TITLE
Referencing host variables under the new List of Dicts schema

### DISCUSSION THREAD

**Discussion by rich9474** [aristanetworks/avd#3024] [Q&A] [answered]
Hi.  I am trying to reference some host variables in a Jinja2 template.  but am unsure of the correct/optimal way of doing it.  In a multi DC config, I have the node types l2leaf, l3leaf and spine for each DC.  For example a l3leaf pair in one:

```
l3leaf:
  node_groups:
    - group: DC1_WAN
      platform: 7280R3
      mlag: false
      nodes:
        - name: loynwan1a
          id: 1
          bgp_as: '65001.1'
          mgmt_ip: 10.255.0.105/24
          mac_address: 11:11:11:11:11:11
          rack: "101"
        - name: loynwan1b
          id: 2
          bgp_as: '65001.2'
          mgmt_ip: 10.255.0.106/24
          mac_address: 22.22.22.22.22.22
          rack: "201"
```
Using the Ansible debugger I can see I can't just reference the `hostvars[host].mgmt_ip` to get the ip address,  but rather every host in that DC of the same node type has a list with all of the other hosts of the same DC/Type in `vars()["task_vars"]["hostvars"][host]["l3leaf"]`.  The host vars will be in a list under either `["node_groups"][group_list_element]["nodes"]` or `["nodes"]`  given nodes are not always in a group, to get to the list of nodes vars I would need to search:

`each group_list_element in vars()["task_vars"]["hostvars"][host]["l3leaf"]["node_groups"][group_list_element]["nodes"]` and
`vars()["task_vars"]["hostvars"][host]["l3leaf"]["nodes"]`

I need to search all lists and return just that hosts entry wherever it is.   but I don't know what node_group the hosts parent is,  I would need to iterate all groups and work out if the host was a member of the ones in this list.  I could then get the groups list of nodes.  For each host, I would need to iterate the node_types, each node_groups and nodes, to work out where the information is.  

To jump through those hoops every time seems like a lot of work and inefficient, so I am guessing/hoping that there is a more elegant way to do this that I am unaware of. If someone can please enlighten me, I would be very grateful.
