### DISCUSSION TITLE
Multiple Static Routes?

### DISCUSSION THREAD

**Discussion by theotherguy2175** [aristanetworks/avd#3116] [Q&A] [answered]
Looking at the examples of AVD for the static_routes example it only ever shows 1 route. But I tried doing this code to get many static routes:

ipv6_static_routes:
  - vrf: default
    destination_address_prefix: 
      - ::/0
      - 2001::32
    gateway: 
      - 2001:xx
      - 2001:xx
      
 And got this error and generated config:

 [WARNING]: [border102.iub]: 'Validation Error: ipv6_static_routes[0].gateway': ['2001:xx', '2001:xx'] is not of type 'str'
 
ipv6 route ['::/0', '2001::32'] ['2001:xx', '2001:xx']

Also on another note this code is for ipv6, which does generate config,

however I have identical config for ipv4, and it never generates 1 or more static routes. Just the default route I defined in my Fabric.yml. Any reason why?

**Comment by ClausHolbechArista** [comment]
Hi @theotherguy2175,

Please refer to the documentation [here](https://avd.sh/en/stable/roles/eos_cli_config_gen/docs/input-variables.html#ipv6-static-routes) and make sure to adhere to the data types described.

Your example should look something like:

```yaml
ipv6_static_routes:
  - vrf: default
    destination_address_prefix: "::/0
    gateway: "2001:xx"
  - vrf: default
    destination_address_prefix: "2001::32"
    gateway: "2001:xx"
```
