### DISCUSSION TITLE
How to setup L3 PortChannel Interface on VRF

### DISCUSSION THREAD

**Discussion by theotherguy2175** [aristanetworks/avd#3117] [Q&A]
In Network services you can define vrfs and then for them to be created as per the documentation there has to be an svi or a l3 interface. Is it possible to define a L3 Port channel? I have tried with this but to no success:

```yaml
      - name: VRF
        vrf_vni: 4094
        l3_interfaces:
          - nodes:
              - border101
              - border102.
            interfaces:
              - Ethernet6 #Goes in order of node (border1)
              - Port-Channel2 #(border2)
            ip_addresses:
              - 10.99.99.66/32
              - 10.99.99.77/30
```
