### DISCUSSION TITLE
Arista AVD Version - v4.3.0- Inventory is generated in different hierarchy

### DISCUSSION THREAD

**Discussion by duddis1** [aristanetworks/avd#3213] [Q&A]
### Issue Summary

Arista AVD Version - v4.3.0- Inventory is generated in different hierarchy

As per the release notes the inventory config has to generated with below hierarchy:
https://avd.sh/en/stable/docs/porting-guides/4.x.x.html#supported-group-structure

The inventory config is currently generated in below hierarchy:
```
inventory.yml
all:
  children:
    RoS_FABRIC:
      children:
        LON:
          children:
            LON_FABRIC:
              children:
                LON_SERVERS:
                  children:
                    LON_IXLEAF: null
                LON_IXLEAF:
                  vars:
                    type: ixleaf
                  hosts:
                    LON-IX-SW:
                      ansible_host: 10.1.10.81/[2](https://gitlab.ros.gov.uk/srt-networks/arista-config-log/-/blob/6ea22a84e012d127069ad16948571cb45254cad4/inventory.yml#L2)4
            LON_TENANTS_NETWORKS:
              children:
                LON_IXLEAF: null
```

Below level of hierarchy is missing from the release notes, but this is needed for the config to be generated.
Can you please validate the above hierarchy whether it meets the criteria?

RoS_FABRIC:
      children:

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI with AVD Runner

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
The example shown in the release-notes you link to are only an example, and only meant for highlighting the mentioned limitation of multiple hierarchies. The amount of groups required depends on the inventory design of each deployment.

I will move this to a discussion, since this is not a bug.

**Comment by ClausHolbechArista** [comment]
> Can you please validate the above hierarchy whether it meets the criteria?

In you inventory layout the group `LON_IXLEAF` has multiple direct "parents" namely `LON_FABRIC` and `LON_SERVERS`. So this inventory would **not** meet the criteria if your `root_container` on the `eos_config_deploy_cvp` task is set to a higher level container.

I suggest changing like this:
```yaml
# inventory.yml
all:
  children:
    RoS_FABRIC:
      children:
        LON:
          children:
            LON_FABRIC:
              children:
                LON_IXLEAF:
                  vars:
                    type: ixleaf
                  hosts:
                    LON-IX-SW:
                      ansible_host: x.x.x.x
    LON_TENANTS_NETWORKS:
      children:
        LON_IXLEAF:
    LON_SERVERS:
      children:
        LON_IXLEAF:
```

This way you can set `RoS_FABRIC` as the `root_container` and it will build the entire hierarchy in Cloudvision.
