### DISCUSSION TITLE
Unexpected Port profile behavior

### DISCUSSION THREAD

**Discussion by reymonlu** [aristanetworks/avd#3332] [General]
Hello,

This is not a bug but an unintended behaviour when using the raw_eos_cli directive in a profile port with the application on a port-channel

### Python
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux

### AVD

TASK [arista.avd.eos_designs : Verify Requirements] 
AVD version 4.4.0

### Configuration 
```yaml
port_profiles:
  - profile: PP_CLUSTER-XXX
    parent_profile: PP_DEFAULTS_ACCESS
    enabled: true
    mode: trunk
    vlans: "1128,2128,1050,2050,4001,20,27,38,45,67,89,99,133,149,203,255,314,324,2001"
    raw_eos_cli: switchport vlan translation 3000-3499 dot1q-tunnel 4001
servers:
  - name: MA-XX-SWAG1
    adapters:
    - endpoint_ports: [ te1/0/37,te1/0/37 ]
      switch_ports: [ Ethernet32, Ethernet34 ]
      switches: [ MA-XXX-LEAF-004,MA-XXX-LEAF-004 ]
      description: "VIRT-MA1: INTERCO LEGACY"
      profile: PP_CLUSTER-MA1-MIGRATION
      port_channel:
        channel_id: 48
        description: "VIRT-MA1: INTERCO LEGACY"
        mode: active
```
### Unexpected generation
```
interface Ethernet32
   description VIRT-XXX: INTERCO LEGACY
   no shutdown
   channel-group 48 mode active
   switchport vlan translation 3000-3499 dot1q-tunnel 4001  -> I do not want it here
!
interface Ethernet34
   description VIRT-XXX: INTERCO LEGACY
   no shutdown
   channel-group 48 mode active
   switchport vlan translation 3000-3499 dot1q-tunnel 4001 -> I do not want it here
!
interface Port-Channel48
   description VIRT-XXX: INTERCO LEGACY_VIRT-XXX: INTERCO LEGACY
   no shutdown
   mtu 9214
   switchport
   switchport trunk allowed vlan 4001,20,27,38,45,67,89,99,133,149,203,255,314,324,2001
   switchport mode trunk
   storm-control broadcast level 1
   storm-control multicast level 1
   storm-control unknown-unicast level 1
   -> I want it here. I know that i could add raw_eos_cli: switchport vlan translation 3000-3499 dot1q-tunnel 4001 under my port-channel configuration but I would prefer to use the profile.
```

Do you guys know how to do it the right way ?

Thanks
