### DISCUSSION TITLE
VLAN approach to port access instead of the other way around

### DISCUSSION THREAD

**Discussion by theotherguy2175** [aristanetworks/avd#3391] [General]
Looking at all the documentation it looks like connected endpoints is the recommendation for switchport vlan access. However this is not very scalable for larger deployments. Is it possible to:

A. Just have configlets like in CVP but somewhere in AVD that can be uploaded to CVP?
B. Is there a more vlan base approach? Something like:

```
vlan_access:
  - id: 10
    ports: ['Ethernet1','Ethernet2']
    mode: access
  - id: 300
    ports: ['Ethernet3,5,7,8,9']
    mode access
```
    
   I feel like something similar to that would be much easier for people who just want to manage VLAN access. For trunks I think connected enpoints makes more sense
