### DISCUSSION TITLE
Interface "LACP Fallback Individual" - qos_profile for members

### DISCUSSION THREAD

**Discussion by PHipnarowicz** [aristanetworks/avd#3794] [Q&A]
Hi AVD Developers,
When creating update_ethernet_interface_cfg function important element is missed. 
This is service_profile getting from qos_profile and that's why port channel members can't inherit QoS settings.
For non-port-channel member, service_profile is extra updated, but for port-channel member with lacp_fallback this step is missed.

Is this something that can be fixed?

**Comment by gmuloc** [comment]
Hi - thanks for reaching out.

Can you please

1. add a snipper of your input variables
2. add the rendered and expected rendered config
3. it seems you are referring to a function in AVD code `update_ethernet_interface_cfg` can you please share a link to the place where you think the issue lies?

Thanks in advance

**Comment by PHipnarowicz** [comment]
Ad1: input variables

```
port_profiles:
  - profile: l2AccessPort
    mode: access
    enabled: true
    qos_profile: "QOS-ALL-PORTS"
    spanning_tree_portfast: edge
    structured_config:
      logging:
        event:
          congestion_drops: true
  - profile: fallbackAccessPort_22
    parent_profile: "l2AccessPort"
    vlans: "22"
```

```
network_ports:
  - switches: ['VHH-P-L5', 'VHH-P-L6']
    switch_ports: ['Ethernet25', 'Ethernet26']
    profile: "l2AccessPort"
    vlans: "22"
    spanning_tree_portfast: edge
    port_channel:
      channel_id: 25
      mode: "active"
      lacp_fallback:
        mode: individual
        timeout: 5
        individual:
          profile: "fallbackAccessPort_22"

```
Ad2: rendered config

```
- name: Port-Channel25
  type: switched
  shutdown: false
  service_profile: QOS-ALL-PORTS
  mode: access
  vlans: '22'
  spanning_tree_portfast: edge
  mlag: 25
  lacp_fallback_mode: individual
  lacp_fallback_timeout: 5

- name: Ethernet25
  peer_type: network_port
  port_profile: l2AccessPort
  shutdown: false
  type: switched
  channel_group:
    id: 25
    mode: active
  mode: access
  vlans: '22'
  spanning_tree_portfast: edge
  logging:
    event:
      congestion_drops: true

- name: Ethernet26
  peer_type: network_port
  port_profile: l2AccessPort
  shutdown: false
  type: switched
  channel_group:
    id: 25
    mode: active
  mode: access
  vlans: '22'
  spanning_tree_portfast: edge
  logging:
    event:
      congestion_drops: true
```

Ad2: expected rendered config

```
- name: Port-Channel25
  type: switched
  shutdown: false
  service_profile: QOS-ALL-PORTS
  mode: access
  vlans: '22'
  spanning_tree_portfast: edge
  mlag: 25
  lacp_fallback_mode: individual
  lacp_fallback_timeout: 5

- name: Ethernet25
  peer_type: network_port
  port_profile: l2AccessPort
  shutdown: false
  type: switched
  channel_group:
    id: 25
    mode: active
  mode: access
  vlans: '22'
  spanning_tree_portfast: edge
  service_profile: QOS-ALL-PORTS  <---
  logging:
    event:
      congestion_drops: true

- name: Ethernet26
  peer_type: network_port
  port_profile: l2AccessPort
  shutdown: false
  type: switched
  channel_group:
    id: 25
    mode: active
  mode: access
  vlans: '22'
  spanning_tree_portfast: edge
  service_profile: QOS-ALL-PORTS  <---
  logging:
    event:
      congestion_drops: true

```
Ad3: 
it refers to change: 
https://github.com/aristanetworks/avd/pull/3510
and the code is in:
ansible_collections/arista/avd/roles/eos_designs/python_modules/connected_endpoints/ethernet_interfaces.py

BR
