### DISCUSSION TITLE
EVPN MLAG iBGP Vlan out of range.

### DISCUSSION THREAD

**Discussion by pradeeprgodhala** [aristanetworks/avd#3974] [Data Model Schemas] [answered]
Hi,

i am trying to use single DC-l3ls data model. under the network services yaml file, i am trying to define the vrf_vni as 54001 for my VRF:PROD, 54002 for my VRF:DEV. But the mlag ibgp vlans generated(57000 for PROD mlag ibgp, 570001 for DEV mlag ibgp) seems to out of range of normal vlans.

however when i change the vrf_vni to 1 for vrf:PROD, and 2 for vrf:DEV. the mlag ibgp vlans are confgured within the range(3000 for PROD mlag ibgp, 3001 for DEV mlag ibgp), seems like there is a 2999 offset value used for creating mlag ibgp vlans for vrf based on the vrf_vni vlaue. 

Can you please tell me, if there is a way to statically define these vlan ID's per VRF.

Thanks
Pradeep

**Comment by ClausHolbechArista** [comment, marked as answer]
Hi Pradeep

The behavior is documented under the `mlag_ibgp_peering_vrfs` key (which I can see ended up in the ["Overlay Settings" section](https://avd.arista.com/4.7/roles/eos_designs/docs/input-variables.html#overlay-settings), which can be a bit confusing. We should move that to network services.

```yaml
# On mlag leafs, an SVI interface is defined per vrf, to establish iBGP peering (required when there are MLAG leafs in topology).
# The SVI id will be derived from the base vlan defined: mlag_ibgp_peering_vrfs.base_vlan + (vrf_id or vrf_vni) - 1.
# Depending on the values of vrf_id / vrf_vni it may be required to adjust the base_vlan to avoid overlaps or invalid vlan ids.
# The SVI ip address derived from mlag_l3_peer_ipv4_pool is re-used across all iBGP peerings.
mlag_ibgp_peering_vrfs:
  base_vlan: <int; 1-4093; default=3000>
```

It is also noted under [Network Services VRF Settings](https://avd.arista.com/4.7/roles/eos_designs/docs/input-variables.html#network-services-vrfs-configuration).

Here is a snip from the `vrf_vni` and `vrf_id` which you could use to get the vlan numbers you need:

```yaml
...
        # Required if "vrf_id" is not set.
        # The VRF VNI range is not limited, but if vrf_id is not set, "vrf_vni" is used for calculating MLAG iBGP peering vlan id.
        # "vrf_vni" may also be used for VRF RD/RT ID. See "overlay_rd_type" and "overlay_rt_type" for details.
        # See "mlag_ibgp_peering_vrfs.base_vlan" for details.
        # If vrf_vni > 10000 make sure to adjust "mac_vrf_vni_base" accordingly to avoid overlap.
        vrf_vni: <int; 1-16777215>

        # Required if "vrf_vni" is not set.
        # "vrf_id" is used as default value for "vrf_vni" and "ospf.process_id" unless those are set.
        # "vrf_id" may also be used for VRF RD/RT ID. See "overlay_rd_type" and "overlay_rt_type" for details.
        # "vrf_id" is preferred over "vrf_vni" for MLAG iBGP peering vlan, see "mlag_ibgp_peering_vrfs.base_vlan" for details.
        vrf_id: <int>
```

So setting `vrf_vni: 54001` and `vrf_id: 1` would give you vlan 3000 for the MLAG peering.

Let me know if this helps.

Thanks
Claus
