### DISCUSSION TITLE
Multiple management Default Gateways in Dual-DC-L3LS.

### DISCUSSION THREAD

**Discussion by pradeeprgodhala** [aristanetworks/avd#3988] [Data Model Schemas] [answered]
Hi,

i am trying to use dual-dcl3ls. but each row in the DC has different GW for the management IP. How do i generate different GW IP for each device. is there a custom mgmt gateway IP key under node_groups or nodes. 

Thanks
Pradeep

**Comment by carlbuchmann** [comment]
Hi @pradeeprgodhala 

No, unfortunately this is not a key available under node_groups or nodes today.
You must create a group_var for each rack and set `mgmt_gateway: <str>`.

**Comment by pradeeprgodhala** [comment]
Thanks @carlbuchmann . Currently we have a spine in each row, does this mean i create a group_vars like this..


DC_ROW_A.yml
DC_ROW_B.yml
DC_ROW_C.yml
DC_ROW_D.yml


Does this also mean. , each group_var yaml file will only contain one spine and the relevant switches that are only in that row ?

**Reply by ClausHolbechArista** [reply]
You can have multi-dimensional inventory trees:

```yaml
all:
  children:
    DC_FABRIC:
      children:
        DC_LEAFS:
          hosts:
            dc-leaf1:
            <...>
        DC_SPINES:
          hosts:
            dc-spine1:
            dc-spine2:
            dc-spine3:
            dc-spine4:
    DC_ROW_A:
      hosts:
        dc-spine1:
        dc-leaf1:
        <...>
    DC_ROW_B:
      hosts:
        dc-spine2:
        dc-leaf17:
        <...>
    <...>
```
