### DISCUSSION TITLE
CVP Topology Tags

### DISCUSSION THREAD

**Discussion by rich9474** [aristanetworks/avd#4060] [Q&A]
I am trying to configure AVD to set the topology tags automatically in CVP.  I have configured in the fabric level yaml:
```
generate_cv_tags:
  topology_hints: true
```
and I now see the tags in the intended structured config metadata for each device:
```
metadata:
  platform: 7280CR3
  cv_tags:
    device_tags:
    - name: topology_hint_datacenter
      value: DC1
    - name: topology_hint_fabric
      value: FABRIC
    - name: topology_hint_pod
      value: POD1
    - name: topology_hint_type
      value: leaf
    - name: topology_hint_rack
      value: CR-712
```
after running the build and provisioning playbooks,  I do not see the tags on CVP either in  Provisioning, Tags, System Tags, or in the Topology view.  What am I missing?

I am also not clear how to set the custom tags on devices.  Say I have a l3 switch pair configured in the DC1.yml l3leaf
```
l3leaf:
  defaults:
    <OMMITED>

  node_groups: 
    - group: DC1_L3_LEAF1
      bgp_as: 65101 
      mlag: true
      nodes:
        - name: dc1-leaf1a
          id: 1
          mgmt_ip: 172.16.1.101/24
          uplink_switch_interfaces: 
            - Ethernet1
            - Ethernet1
        - name: dc1-leaf1b
          id: 2
          mgmt_ip: 172.16.1.102/24
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2
```
I want to set three tags on this:

1. AVD_Type:L3Leaf
2. MLAG:True
3. Leaf_Pair:A   # Depending on if it is A or B in the pair

I thin use these tags in the upgrade template, and associated tasks.
The main questions I have is:

1. can I set the ``MLAG: true`` tag based on the mlag variable in eos_design?
2. can I set the A or B variable based on the last letter of the hostname?
3. If I have to manually set these variables, where do I put them in the eos_design hierarchy?  I have also tried setting them under a ``structured_config`` dict, but it seemed to have no effect.

**Comment by jonxstill** [comment]
Hi Rich,

The existing `eos_config_deploy_cvp` role will not push these tags into Cloudvision.  To do that you need to use the newer `cv_deploy` role: https://avd.sh/en/stable/roles/cv_deploy/index.html

However:
  - This is very new code.
  - It requires CloudVision 2024.1.0 or later,  or CVaaS.
  - It does not create configlets, or the container hierarchy that you normally see under "Network Provisioning".
  - Instead it uses the Static Configuration Studio - this essentially drives a whole new provisioning stack within CloudVision.
  - Try this in the lab first please!

Coming back to your questions:
  - Currently the `data_path` variable under `device_tags` can only be set to data paths found within the device's structured_configuration - basically if it's in the YAML file generated by `eos_designs`, then you should be able to use it.

I've asked some questions internally around your questions and will come back to you as soon as possible.

Jon.

**Reply by ClausHolbechArista** [reply]
Thanks Jon.
Another option is to use `arista.cv.cv_tags_v3` but it might require some adjustment of the data model.

**Comment by chetryan** [comment]
Hi Rich,

Assuming you have a dedicated group in the inventory for the L3 Leafs that have MLAG enabled, you could add the below to that groups' yaml file (example: `DC1_L3_LEAVES.yml` )

```
generate_cv_tags:
  topology_hints: true
  device_tags:
    - name: AVD_Type
      value: L3Leaf  # I am assuming all the switches in this group are L3 Leafs
    - name: MLAG
      value: True  # I am assuming that all the switches in this group have MLAG enabled
    - name: Leaf_Pair
      value: "{{ hostname[-1] | upper }}" # assumes that the A vs B you are looking is the suffix in the hostname

```

**Reply by rich9474** [reply]
Not all switches will have MLAG.  Can some similar Jinja2 templating be done to lookup the device mlag variable?

**Reply by rich9474** [reply]
I am looking at setting the tags using the ``arista.cv.cv_tags_v3`` module, and generating the tags var is relatively easy.  Because a device can have more than one tag value of the same name, it is not sufficient to just set the tag again if it changes,  I need to delete incorrect ones as well.  For example.  If a switch has the ``MLAG: true`` tag set, and I set the ``MLAG: false`` tag, it now has both tags, which is not what I want.   How can I get a list of current tags from the CVP server, so I can calculate the diff and what I need to delete?  

edit:   I just worked out why the cv_facts_v3 wasn't working,  I was running it against devices, not the specific CVP SServer host entry in the inventory.

**Comment by philippebureau** [comment]
i am getting errors when trying to push tags with deploy_cv to CVaaS

avd 4.8
```
The full traceback is:
Traceback (most recent call last):
  File "/home/pbureau/Documents/GitHub/ansible-cvp/ansible_collections/arista/avd/plugins/action/cv_workflow.py", line 132, in deploy
    result_object = await deploy_to_cv(
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/pbureau/Documents/GitHub/ansible-cvp/ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/deploy_to_cv.py", line 152, in deploy_to_cv
    await deploy_tags_to_cv(
  File "/home/pbureau/Documents/GitHub/ansible-cvp/ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/deploy_tags_to_cv.py", line 68, in deploy_tags_to_cv
    await cv_client.set_tags(workspace_id=workspace.id, tags=[(tag.label, tag.value) for tag in tags_to_add], element_type=tag_type)
  File "/home/pbureau/Documents/GitHub/ansible-cvp/ansible_collections/arista/avd/plugins/plugin_utils/cv_client/client/tag.py", line 174, in set_tags
    raise get_cv_client_exception(e, f"Workspace ID '{workspace_id}', Element Type '{element_type}'") or e
  File "/home/pbureau/Documents/GitHub/ansible-cvp/ansible_collections/arista/avd/plugins/plugin_utils/cv_client/client/tag.py", line 168, in set_tags
    async for response in responses:
  File "/home/pbureau/Documents/GitHub/ansible-cvp/ansible_collections/arista/avd/plugins/plugin_utils/cv_client/api/arista/tag/v2/__init__.py", line 1829, in set_some
    async for response in self._unary_stream(
  File "/home/pbureau/VENV/AVD/lib/python3.11/site-packages/aristaproto/grpc/grpclib_client.py", line 100, in _unary_stream
    async with self.channel.request(
  File "/home/pbureau/VENV/AVD/lib/python3.11/site-packages/grpclib/client.py", line 553, in __aexit__
    await self._maybe_finish()
  File "/home/pbureau/VENV/AVD/lib/python3.11/site-packages/grpclib/client.py", line 523, in _maybe_finish
    await self.recv_trailing_metadata()
  File "/home/pbureau/VENV/AVD/lib/python3.11/site-packages/grpclib/client.py", line 484, in recv_trailing_metadata
    self._raise_for_grpc_status(status, message, details)
  File "/home/pbureau/VENV/AVD/lib/python3.11/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'failed to write 40 items', None)
fatal: [dc2-spine1 -> localhost]: FAILED! => changed=false 
  msg: 'Error during plugin execution: (<Status.INTERNAL: 13>, ''failed to write 40 items'', None)'
```

**Comment by rich9474** [comment]
So I have a current playbook that appears to achieve what I want from a setting the tags perspective

```yaml
---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: FABRIC
  connection: local
  gather_facts: false
  debugger: on_failed
  collections:
    - arista.avd
    - arista.cvp
  vars_files:
    - "{{inventory_dir}}/secrets/vault.yml"
  vars:
    CVP_TAGS: []

  tasks:
    - name: Include Vault Vars to workaround bug
      ansible.builtin.include_vars:
        file: "{{inventory_dir}}/secrets/vault.yml"
      tags: always
      run_once: true


    - name: generate intended variables
      import_role:
        name: arista.avd.eos_designs

    - name: 'device_id'
      set_fact:
        device_id: "{{ switch.serial_number }}"

    - name: Generate base device_tags vars
      set_fact:
        device_tags:
          - name: "MLAG"
            value: "{{ (switch.mlag_peer is defined) | string }}"
          - name: "AVD_Type"
            value: "{{ switch.type }}"

    - name: Add Leaf_Pair to device_tags if hostname ends with 'a'
      set_fact:
        device_tags: "{{ device_tags + [{'name': 'Leaf_Pair', 'value': 'A'}] }}"
      when: hostname[-1] == 'a'

    - name: Add Leaf_Pair to device_tags if hostname ends with 'b'
      set_fact:
        device_tags: "{{ device_tags + [{'name': 'Leaf_Pair', 'value': 'B'}] }}"
      when: hostname[-1] == 'b'

    - name: Add metadata.cv_tags.device_tags to device_tags
      set_fact:
        device_tags: "{{ device_tags + hostvars[inventory_hostname]['metadata']['cv_tags']['device_tags'] }}"
      when: hostvars[inventory_hostname]['metadata']['cv_tags']['device_tags'] is defined

    - name: Build CVP_TAGS list
      set_fact:
        CVP_TAGS: "{{ CVP_TAGS + [{'device_id': hostvars[item]['device_id'], 'device_tags': hostvars[item]['device_tags']}] }}"
      loop: "{{ groups['all'] }}"
      when: hostvars[item]['device_tags'] is defined
      run_once: true
      delegate_to: localhost
      delegate_facts: true

    - name: Write CVP_TAGS to a file in the debug directory
      ansible.builtin.copy:
        content: "{{ hostvars['localhost']['CVP_TAGS'] | to_nice_yaml }}"
        dest: "../debug/CVP_TAGS.yaml"
      run_once: true
      delegate_to: localhost


- name: Send Tags to server
  hosts: cv_server
  vars_prompt:
    - name: cvp_pass
      prompt: "Enter your CVP password ?"
  tasks:
    - name: get CVP_TAGS from hostvars.localhost.CVP_TAGS variable
      ansible.builtin.set_fact:
        CVP_TAGS: "{{ hostvars['localhost']['CVP_TAGS'] }}"
      run_once: true
      delegate_to: localhost

    - name: "create tags"
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS}}"
        mode: assign
        auto_create: true
```
This is fine initially setting the tags.  What I also need to do is make sure that mutually exclusive tags are not set to both.  for example, if a switch was configured for MLAG, and has the `MLAG: true` tag set, then when I set the `MLAG: false` tag, I need to remove the other one or they will both be set.  It seems that tags do not need to be unique.  Is there a way to replace rather than add a Tag Key:Value pair, or how can I enumerate the currently set tags for a device, so I can tell if I need to remove one.
