### DISCUSSION TITLE
Directly set IPs for router_id and vtep for a node

### DISCUSSION THREAD

**Discussion by jmussmann** [aristanetworks/avd#4164] [Ideas]
When using an IPAM tool like netbox it might be helpful to directly set the IP address for the  loopback devices (router_id and VTEP).

To support this I would suggest to add "loopback_ipv4" and "vtep_loopback_ipv4" parameters to nodes.
These parameters, if set, would override the pool setting.

Example:
```
# Spine switch group
spine:
  # Definition of default values that will be configured to all nodes defined in this group
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: cEOSLab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # ASN to be used by BGP
    bgp_as: 65100

  # Definition of nodes contained in this group.
  # Specific configuration of device must take place under the node definition. Each node inherits all values defined under 'defaults'
  nodes:
    # Name of the node to be defined (must be consistent with definition in inventory)
    - name: dc1-spine1
      # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
      id: 1
      # Management IP to be assigned to the management interface
      mgmt_ip: 172.16.1.11/24
      loopback_ipv4: 10.255.0.1

    - name: dc1-spine2
      id: 2
      mgmt_ip: 172.16.1.12/24
      loopback_ipv4: 10.255.0.2
```

I am already working on that feature.
Would this be something someone else is interested in.
