### DISCUSSION TITLE
postcard telemetry and PTP profile g8275.1 in AVD?

### DISCUSSION THREAD

**Discussion by rradim** [aristanetworks/avd#4204] [Ideas]
Hello,

wondering if there is a plan to implement **postcard telemetry** configuration in the AVD. We are currently working with one "AVD" customer in POC of this feature and considering deploying it in production. 

Also it would be useful to have support of more PTP profiles - customer is using g8275.1...we eventually used interface profiles to implement it :)...but current PTP support is there, so it just did not support our desired profile...

```
custom_structured_configuration_interface_profiles:
    # Interface-Profile Name
  - name: PTP_port_profile
    commands:
      - ptp enable
      - ptp transport layer2
      - ptp delay-mechanism e2e
      - ptp profile g8275.1 destination mac-address forwardable
```
