### DISCUSSION TITLE
Arista AVD: group_vars, Fabric.yml file update for new leaf with different model and uplink ports

### DISCUSSION THREAD

**Discussion by razizaheer1** [aristanetworks/avd#4400] [Q&A] [answered]
Hi Community,

I'm relatively less experience with AVD as mainly update existing or new end point and minor configuration changes, which is a regular task. However, I'm currently faced with the need to incorporate new leaf switches into an existing Fabric. These new switches have a different model and uplink ports compared to the existing leaf switches. I'm seeking guidance on how to add these new leaf peers in AVD without disrupting the current setup and IP allocation.

Model of new leafs: 7050CX3
Uplink port towards spine: Ethernet29/1', 'Ethernet30/1'

Current AVD fabric.yml
```yaml
#
l3leaf:
  defaults:
    platform: 7280R2
    loopback_ipv4_pool: 
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 
    uplink_interfaces: ['Ethernet49/1', 'Ethernet54/1']
    uplink_switches: ['SPNSWT001', 'SPNSWT002']
    uplink_ipv4_pool:
    mlag_interfaces: [ 'Ethernet51/1', 'Ethernet52/1' ]
    mlag_peer_ipv4_pool: 
    mlag_peer_l3_ipv4_pool: 
```

**Comment by ClausHolbechArista** [comment, marked as answer]
Below the section you have shared, you will likely see `node_groups`. Each group is an MLAG pair. Under each group you will see `nodes` with the individual leaf switches. Each switch have a unique ID which is used to allocate IP addresses for uplinks and loopbacks. For each switch you will also see the `uplink_switch_interfaces` which is the port on each spine, used to connect to this device.

To add you new leaf pair you just add a new group and since you need to override some settings from the defaults, you can set them under the node group like this:

```yaml
l3leaf:
  defaults:
    platform: 7280R2
    loopback_ipv4_pool: 
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 
    uplink_interfaces: ['Ethernet49/1', 'Ethernet54/1']
    uplink_switches: ['SPNSWT001', 'SPNSWT002']
    uplink_ipv4_pool:
    mlag_interfaces: [ 'Ethernet51/1', 'Ethernet52/1' ]
    mlag_peer_ipv4_pool: 
    mlag_peer_l3_ipv4_pool: 
  node_groups:
    <... - all the existing node groups>

    - group: <name of new leaf pair>
      platform: 7050X3  # <-- Overriding the platform from 'defaults'
      uplink_interfaces: ['Ethernet29/1', 'Ethernet30/1']  # <-- Overriding the uplink_interfaces from 'defaults'
      mlag_interfaces: ['Ethernet31/1', 'Ethernet32/1']  # <-- Guessing here, so update as you need
      nodes:
        - name: <name of first leaf>
          id: <next available id>
          uplink_switch_interfaces: [<interface on spine1>, <interface on spine2>]
        - name: <name of second leaf>
          id: <next available id>
          uplink_switch_interfaces: [<interface on spine1>, <interface on spine2>]
```
