### DISCUSSION TITLE
access_lists overwritten when defined in fabric, datacenter and as structured_config under a vrf

### DISCUSSION THREAD

**Discussion by PieterL75** [aristanetworks/avd#4445] [Q&A]
the definition of access_lists is overwritten by higer level of definitions
If I define an access_lists section in the 'fabric' and then one in the 'datacenter', the access_lists of the fabric is gone. I would expect them to be merged.
I tried "access_lists" in the fabric and "custom_structured_configuration_access_lists" in the 'datacenter', but that just doesn't stick. or even "custom_structured_configuration_access_lists" in both fabric and datacenter...

also, in Network_service, on a VRF, when I set a
```
        structured_config:
          access_lists:
            - name: SEC-SNMP_VRF_MIRROR-V4-IN
              sequence_numbers:
                - sequence: 10
                  action: permit host 100.74.2.130
```
it removes other already defined accesslist in the fabric or datacenter
