### DISCUSSION TITLE
shutdown all ports by default

### DISCUSSION THREAD

**Discussion by PieterL75** [aristanetworks/avd#4460] [FAQ]
What is the best way to disable all ports that are not used ?
I tried with
```
interface_defaults:  
  ethernet:
    shutdown: true
```
but the arista's then also generate interfaces for all 'lanes', even if there is SFP or what ever installed..

then I tried
```
network_ports:
  - switches: 
      - .*-lfs-.*
      - .*-dci-.*
    switch_ports: 
      - Ethernet1-48
      # - Ethernet49-52/1  ## do not shutdown these. Those are the MLAG en SPINE uplinks.
      - Ethernet53-56/1
    enabled: false
    description: "shutdown"

```
that works. but it will also shutdown any l3-interfaces that I have defined.

any suggestion on what the best approach ?
