### DISCUSSION TITLE
apply route-map and prefix-list only to nodes that have the BGP peering applied

### DISCUSSION THREAD

**Discussion by PieterL75** [aristanetworks/avd#4559] [Q&A] [answered]
I have a tenant with a vrf. That vrf has SVI's over 6 nodes.
one node forsees external BGP peerings and those are secured with route-map and prefix-lists.
I used the vrf/structured_config to define the routemap and prefix lists. 

But now I see that those are applied to all nodes, and not only to the those with the BGP peering..

Is there a cleaner way to do this ? I don't like that orphaned config, as it looks like something was configured incorrect

**Comment by ClausHolbechArista** [comment]
For now the only way would be to use some inline-jinja to check if you are on one of the 6 nodes.

Written from memory, to may need some adjustment. Refer to Ansible docs for guidance.

```yaml
structured_config: |-
  {% if inventory_hostname in ['node1', 'node2'] %}
  route_maps: ...
  {% elif %}
  null
  {% endif %}
```

We have implemented `ipv4_prefix_list_catalog`, but it is currently only used by `l3_interfaces` defined under the nodes.

We would like to implement similar "catalogs" of route-maps and other areas which will be applied when referred to under the BGP peers, peer-groups etc. So the route-maps and prefix-lists them selves would also get proper models in eos_designs.

**Reply by ClausHolbechArista** [reply]
BTW this structured config would go under the VRF, since structured config there is placed at the root of the eos_cli_config_gen model.

**Reply by PieterL75** [reply]
Looks promising.
thx for the fast feedback

**Reply by PieterL75** [reply]
I ended up creating separate host-groups in my inventory file.
and then a group_var per group of devices that have `custom_structured_configuration_myhostgroup_prefix_lists`
that way I can control what prefixlist/routemap shows up on what devices.

not ideal, as I have to manually update the inventory file when a new device is added and needs those prefix/route-maps

**Comment by PieterL75** [comment, marked as answer]
I wrote a 'conditional catalog' to kind of get around it..
There is a catalog created like this 
```
_catalog_prefix_lists:
  - name: PL-BE-EBGP4-DEFAULT
    _apply_groups:
      - FABRIC
    _apply_hosts:
    sequence_numbers:
      - sequence: 10
        action: permit 0.0.0.0/0

_catalog_ipv6_prefix_lists:
  - name: PL-BE-EBGP6-DEFAULT
    _apply_groups:
      - FABRIC
    _apply_hosts:
    sequence_numbers:
      - sequence: 10
        action: permit ::/0
```
any design variable can be appended to \_catalog\_ 
- prefix_lists
- route_maps
- match_list
- and so one

then I added a custom_structured_configuration_prefix `generated_`
```
custom_structured_configuration_prefix:  
  - custom_structured_configuration_
  - generated_
```
and an ansible set_fact
```
    - name: Build Conditional Catalogs # noqa: run-once[task]
      # yamllint disable rule:line-length
      ansible.builtin.set_fact:
        "generated_{{ item | replace('_catalog_', '') }}": "{% set catalog = query('ansible.builtin.vars', item) | first %}{% if catalog | default(None) %}{% set ns = namespace(result=[]) %}{% for catalogitem in catalog %}{% if ('_apply_groups' in catalogitem and catalogitem._apply_groups and group_names | select('in', catalogitem._apply_groups) | list | count > 0) or ('_apply_hosts' in catalogitem and catalogitem._apply_hosts and inventory_hostname in catalogitem._apply_hosts) %}{% set ns.result = ns.result + [dict(catalogitem.items() | rejectattr(0, 'in', ['_apply_groups', '_apply_hosts'] | list))] %}{% endif %}{% endfor %}{{ ns.result }}{% endif %}"
      # yamllint enable rule:line-length
      with_items: "{{ query('ansible.builtin.varnames', '^_catalog_.+') }}"
```
now any variable starting with _catalog_ will create a generated_ variable, and only if any of the apply_group is part of the ansible groups, or if the inventory_hostname matches the hostname

Works pretty good :-)

of course, I still have to manually decide what prefix list, route map, access-list goes on what devices, but at least they are not lingering on devices they are not needed on

@ClausHolbechArista
