### DISCUSSION TITLE
Dualsided MLAG

### DISCUSSION THREAD

**Discussion by PieterL75** [aristanetworks/avd#4582] [Q&A] [answered]
I have a device that is also doing MLAG (Cisco with vPC).
this means that 4 interfaces (2 on each leaf) are in one MLAG id on the leaf side.

How do I model that connection in AVD? 

I tried with 
ENDPOINTS.YML
```
switches:
  - name: rtr-coreacc003
    adapters:
      - endpoint_ports: [Ethernet1/29, Ethernet1/30]
        switch_ports: [Ethernet7, Ethernet7]
        switches: [dci-215-a1-p01, dci-215-b1-p01]
        port_channel:
          description: Port-Channel60
          mode: active
          channel_id: 60
  - name: rtr-coreacc004
    adapters:
      - endpoint_ports: [Ethernet1/29, Ethernet1/30]
        switch_ports: [Ethernet8, Ethernet8]
        switches: [dci-215-a1-p01, dci-215-b1-p01]
        port_channel:
          description: Port-Channel60
          mode: active
          channel_id: 60
```
but that failed due to the duplicate channelid.

**Comment by ClausHolbechArista** [comment, marked as answer]
```yaml
switches:
  - name: rtr-coreacc003_rtr-coreacc004
    adapters:
      - endpoint_ports: [Ethernet1/29, Ethernet1/30, Ethernet1/29, Ethernet1/30]
        switch_ports: [Ethernet7, Ethernet7, Ethernet8, Ethernet8]
        switches: [dci-215-a1-p01, dci-215-b1-p01, dci-215-a1-p01, dci-215-b1-p01]
        port_channel:
          description: Port-Channel60
          mode: active
          channel_id: 60
```
