### DISCUSSION TITLE
add support for unix-socket protocol and fips_restrictions

### DISCUSSION THREAD

**Discussion by KrasenKolev** [aristanetworks/avd#4588] [Ideas]
Hello,   

Few months ago I started using AVD to build new network and now I also use it to maintain it, so I am keen in contributing to the project. As I am not a developer, but still interested in network automation, I would like to raise some simple improvement ideas that I can potentially work on during my free time.

1. Add support for fips restrictions under management security -> ssl profile.  In eos_cli_config_gen role -> management_ssh there is support for fips restrictions, but it’s missing in ssl profile.  

```
management_security:
## OMIT ##
  ssl_profiles:
    - name: <str>
      tls_versions: <str>
      fips_restrictions: <bool> 
      ## OMIT ##
``` 

2. add support for protocol unix-socket under management api https-commands In management_api_http there is boolean for http and https protocols, but it’s missing for unix-socket.

```
management_api_http:
  enable_http: <bool>
  enable_https: <bool>
  enable_unix_socket: <bool>
  ## OMIT ##
``` 

Kind Regards,
Krasen
