### DISCUSSION TITLE
avd 5.0.0 - unable to set a port to 'routed' mode

### DISCUSSION THREAD

**Discussion by PieterL75** [aristanetworks/avd#4671] [Q&A] [answered]
We have portchannel interfaces that have layer3 subinterfaces.
I always set the interface to 'type: routed' using custom_config in a port-profile but that is no longer possible in avd 5.0.0.

```
  - profile: BEAZ1_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST
    enabled: true
    flow_tracking:
      enabled: false
    structured_config:
      type: routed
    port_channel:
      lacp_timer:
        mode: fast
```

How can I for a port to be in 'no switchport' ?

**Comment by gmuloc** [comment, marked as answer]
You can use 
```
switchport:
  enabled: false
```

**Reply by PieterL75** [reply]
Sometimes it can be sooo easy :-)

```
  - profile: BEAZ1_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST
    enabled: true
    flow_tracking:
      enabled: false
    structured_config:
      switchport:
        enabled: false
    port_channel:
      lacp_timer:
        mode: fast
```

works perfect !
