### DISCUSSION TITLE
Is it possbile to define l3_edge links in to different yaml files and then both be used in avd

### DISCUSSION THREAD

**Discussion by geckigek** [aristanetworks/avd#4868] [Q&A] [answered]
Hello AVD community,

I would like to maintain two separate YAML files for different link definitions — for example, one for “Connected Endpoints” and another for “Essential Links.” Ultimately, I need to feed all of these links into the same l3_edge structure that the AVD solution expects.

Instead, I want to merge both sets of link data into a single variable (l3_edge) at runtime using Ansible’s variable-merging capabilities. The challenge is that we have list data (e.g., p2p_links), which typically gets overwritten rather than merged unless extra steps are taken.

Below is a simplified, anonymized example to illustrate what I mean:

```
# group_vars/CONNECTED_ENDPOINTS/connected_endpoints.yml
connected_endpoints_l3_edge:
  p2p_links_profiles:
    - name: LINK-PROFILE_STREAMINGPORTS
      ptp:
        enabled: true
    # ...
  p2p_links:
    - nodes:
        - endpoint-a
        - leaf-1
      interfaces:
        - Ethernet5
        - Ethernet2
      profile: LINK-PROFILE_STREAMINGPORTS
    # ...
```

```
# group_vars/ESSENTIAL_LINKS/essential_links.yml
essential_links_l3_edge:
  p2p_links_profiles:
    - name: LINK-PROFILE_FOO
      ptp:
        enabled: false
    # ...
  p2p_links:
    - nodes:
        - borderleaf-a
        - borderleaf-b
      interfaces:
        - Ethernet48
        - Ethernet52
      profile: LINK-PROFILE_FOO
    # ...
```
Finally, I would like to produce a combined l3_edge variable that includes both sets of data, for example:

```
l3_edge:
  p2p_links_profiles:
    - name: LINK-PROFILE_STREAMINGPORTS
      ptp:
        enabled: true
    - name: LINK-PROFILE_FOO
      ptp:
        enabled: false
  p2p_links:
    # ...
```
Question:
How can I cleanly merge these two separate YAML structures into one l3_edge variable without modifying any of the AVD Jinja templates?

Are there recommended best practices for list merging in Ansible (e.g., using combine, list_merge='append', etc.) to handle this scenario?

Are there any pitfalls I should watch out for when managing separate files at the group_vars level and merging them in a “final” file (e.g., group_vars/all)?
