### DISCUSSION TITLE
L3Spine with external BGP Peers

### DISCUSSION THREAD

**Discussion by SomaliRaven** [aristanetworks/avd#5085] [FAQ]
Hi,
I would like to add a l3spine which provides separate VRFs (including default VRF) with multiple SVI and connected endpoints. In each VRF external BGP Peers have to  be configured. In the current definition VRFs, SVI and everything else is generated. The BGP configuration does not get generated. 

```
### AVD switch role  ###
node_type_keys:
  - key: l3spine
    type: l3spine
    connected_endpoints: true
    mlag_support: true
    network_services:
      l2: true
      l3: true
    underlay_router: true
    default_overlay_routing_protocol: none
    default_underlay_routing_protocol: none
```   

If i change `default_overlay_routing_protocol: eBGP`, `default_underlay_routing_protocol: eBGP` i get a basic router bgp configuration with the peer groups but no vrf and neighbor configuration. 

```
tenants:
  - name: Tenant_DC
    vrfs:
      - name: default
        mlag_ibgp_peering_vlan: 4093
        mlag_ibgp_peering_ipv4_pool: "{{ mlag_peer_l3_ipv4_pool }}"
        svis:
          - id: 999
            name: transit-core
            tags: [transit]
            enabled: true
            igmp_snooping_enabled: true
            ip_virtual_router_addresses:
              - {{ transfer_vip }}
            nodes:
              - node: core-01
                ip_address: {{ transfer_ip_core-01 }}
              - node: core-02
                ip_address: {{ transfer_ip_core-02 }}
            mtu: 1500
        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: "{{ fw_nexthop }}"
        bgp_peer_groups:
          - name: IPv4-PEER-CORE
            maximum_routes: 100
            send_community: all
            local_as: "{{ bgp_as_dc_out }}"
            route_map_in: RM-Tenant_LAN-CORE_IN
            route_map_out: RM-Tenant_LAN-CORE_OUT
            nodes: [core-01, core-02]
            remote_as: "{{ bgp_as_lan_core }}"

        bgp_peers:
          - ip_address: {{ transfer_ip_lan_core }}
            nodes: [core-01, core-02]
            peer_group: IPv4-PEER-CORE
            update_source: Vlan999
 ```

Did anyone have a similiar setup and a solution for this problem using the eos_design role?
