### DISCUSSION TITLE
Requirement for EVPN overlay

### DISCUSSION THREAD

**Discussion by Olen** [aristanetworks/avd#5118] [Data Model Schemas] [answered]
We are building the AVD config from external sources (like Netbox) and are getting very close to a fully working model.
However I am unable to get AVD to build a EVPN/VXLAN overlay for l2 transport.
 
We have a simple working example using static yaml, but the dynamically generated config does not build the overlay.
The whole generated yaml is probably to long to post here, but what I thought was the relevant bits are the following:

```
node_type_keys:
- key: l3leaf
  type: l3leaf
- key: spine
  type: spine


network_services_keys:
- name: tenant_l2_vlans

l3leaf:
  nodes:
  - id: 1
    name: leaf-1
    uplink_interfaces:
    - Ethernet49/1
    - Ethernet50/1
    - Ethernet51/1
    uplink_switch_interfaces:
    - Ethernet1/1
    - Ethernet2/1
    - Ethernet19/1
    uplink_switches:
    - spine-1
    - spine-1
    - spine-1

spine:
  nodes:
  - id: 1
    name: spine-1

tenant_l2_vlans:
- l2vlans:
  - id: 65
    name: Vlan-Name
  mac_vrf_vni_base: 2190000

underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

```
(Of course we have a lot more config, this is just a sample)

So the leafs are defined as `l3leaf`s and I have a l2tenant with some VLANs and a `mac_vrf_vni_base`
The spines are defined as `spine`s

This seems to match the simple static config, but something is obviously missing.

My config configures L3-tenants, and it creates the VLANs, and I am amble to create both trunk- and access-ports in said VLANs 
 
When I run `pyavd.validate_inputs(inputs)` I don't get any errors.

When I run a `result = pyavd.get_avd_facts(all_inputs=all_inputs)` I get a parsed result back whch contains 
```
{
  'avd_overlay_peers': {},
  'avd_switch_facts': {
...
    'overlay': {
      'evpn_mpls': False,
      'peering_address': '10.250.194.21'
    },
```
The peering_address matches the router-id for each host.
But the overlay_peers is empty.

I have read the entire documentation for AVD multiple times, and most of the source on github (at least it feels like that) but trying to gather exactly what is required for a feature to be activated by AVD - EVPN Overlay in this case) is not really obvious. 

The source for pyavd seems to be using this function to get the overlay peers:
https://github.com/aristanetworks/avd/blob/1a8d7e247e2ba35d1714b27bde9e7212bdd58bbb/python-avd/pyavd/get_avd_facts.py#L140

Which does
```
        host_evpn_route_servers = avd_switch_facts[hostname]["switch"].get("evpn_route_servers", [])
```

Which again seems to suggest that the route servers should automatically be populated from the "uplink_switches"

https://github.com/aristanetworks/avd/blob/1a8d7e247e2ba35d1714b27bde9e7212bdd58bbb/python-avd/pyavd/_eos_designs/eos_designs_facts/overlay.py#L32
>         For evpn clients the default value for EVPN Route Servers is the content of the uplink_switches variable set elsewhere.

So what exactly is the minimum requirements for an EVPN overlay to be formed?

Where should I "start" digging?

**Comment by gmuloc** [comment, marked as answer]
Hi @Olen it seems you are overwriting the default `node_type_keys` - you should not as this is what determine the behavior for a node which should unlock you:

```
node_type_keys:
- key: l3leaf
  type: l3leaf
- key: spine
  type: spine
```


you are missing quite a few keys in there as compared to the defaults (in particular the EVPN role and whether or not to enable l2 and l3 services):

```
node_type_keys:

  - key: spine
    type: spine
    default_evpn_role: server
    default_ptp_priority1: 20
    cv_tags_topology_type: spine

  - key: l3leaf
    type: l3leaf
    connected_endpoints: true
    default_evpn_role: client
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true
    default_ptp_priority1: 30
    cv_tags_topology_type: leaf
