### DISCUSSION TITLE
Node Platform Definitions

### DISCUSSION THREAD

**Discussion by dankuednet** [aristanetworks/avd#5309] [General]
From my understanding, to design a network that matches our hardware, I'll need to define our Arista devices because our physical devices are not available to be queried and the vEOS virtual lab devices are not the same as our physical devices.

I haven't been able to get the platform specification to induce a change.  The devices I'm working with are 7050TX-48, 720XP-48ZC2, 7060CX-32S.  Maybe I'm not using the correct Arista Platform Family designations?  Is there a list of valid Arista Platform Family values?

**Comment by ClausHolbechArista** [comment]
They are listed under the documentation here: https://avd.arista.com/devel/ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.html#platform-settings.

But they can be a bit hard to find. If you go to the YAML tab and scroll down to the platform_settings:
![image](https://github.com/user-attachments/assets/c24b9da0-1c80-414d-acd6-cce7b9fcbaf5)

Click on the small (+) and you will get the default information. Included here for your convenience.
Notice it is the values under `platforms` that can be assigned as `platform: <value>`. If you wish to provide your own, you should use `custom_platform_settings` so they can be added side-by-side with the builtin ones.

```yaml
platform_settings:
- feature_support:
    queue_monitor_length_notify: false
  platforms:
  - default
  reload_delay:
    mlag: 300
    non_mlag: 330
- feature_support:
    queue_monitor_length_notify: false
  platforms:
  - 7050X3
  reload_delay:
    mlag: 300
    non_mlag: 330
  trident_forwarding_table_partition: flexible exact-match 16384 l2-shared 98304 l3-shared
    131072
- feature_support:
    poe: true
    queue_monitor_length_notify: false
  platforms:
  - 720XP
  reload_delay:
    mlag: 300
    non_mlag: 330
  trident_forwarding_table_partition: flexible exact-match 16000 l2-shared 18000 l3-shared
    22000
- feature_support:
    poe: true
    queue_monitor_length_notify: false
  management_interface: Management0
  platforms:
  - '750'
  - '755'
  - '758'
  reload_delay:
    mlag: 300
    non_mlag: 330
- feature_support:
    poe: true
    queue_monitor_length_notify: false
  platforms:
  - 720DP
  - 722XP
  - 710P
  reload_delay:
    mlag: 300
    non_mlag: 330
- feature_support:
    per_interface_mtu: false
    queue_monitor_length_notify: false
  platforms:
  - 7010TX
  reload_delay:
    mlag: 300
    non_mlag: 330
- lag_hardware_only: true
  platforms:
  - 7280R
  - 7280R2
  - 7020R
  reload_delay:
    mlag: 900
    non_mlag: 1020
  tcam_profile: vxlan-routing
- platforms:
  - 7280R3
  reload_delay:
    mlag: 900
    non_mlag: 1020
  tcam_profile: vxlan-routing
- lag_hardware_only: true
  management_interface: Management0
  platforms:
  - 7500R
  - 7500R2
  reload_delay:
    mlag: 900
    non_mlag: 1020
  tcam_profile: vxlan-routing
- management_interface: Management0
  platforms:
  - 7500R3
  - 7800R3
  reload_delay:
    mlag: 900
    non_mlag: 1020
  tcam_profile: vxlan-routing
- feature_support:
    bgp_update_wait_for_convergence: true
    bgp_update_wait_install: false
    interface_storm_control: true
    queue_monitor_length_notify: false
  management_interface: Management1/1
  platforms:
  - 7358X4
  reload_delay:
    mlag: 300
    non_mlag: 330
- management_interface: Management0
  platforms:
  - 7368X4
  reload_delay:
    mlag: 300
    non_mlag: 330
- management_interface: Management0
  platforms:
  - 7300X3
  reload_delay:
    mlag: 1200
    non_mlag: 1320
  trident_forwarding_table_partition: flexible exact-match 16384 l2-shared 98304 l3-shared
    131072
- feature_support:
    bgp_update_wait_for_convergence: false
    bgp_update_wait_install: false
    interface_storm_control: false
    queue_monitor_length_notify: false
  platforms:
  - VEOS
  - VEOS-LAB
  - vEOS
  - vEOS-lab
  reload_delay:
    mlag: 300
    non_mlag: 330
- feature_support:
    bgp_update_wait_for_convergence: false
    bgp_update_wait_install: false
    interface_storm_control: false
    queue_monitor_length_notify: false
  management_interface: Management0
  platforms:
  - CEOS
  - cEOS
  - ceos
  - cEOSLab
  reload_delay:
    mlag: 300
    non_mlag: 330
- feature_support:
    bgp_update_wait_for_convergence: true
    bgp_update_wait_install: false
    interface_storm_control: false
    platform_sfe_interface_profile:
      max_rx_queues: 6
      supported: true
    queue_monitor_length_notify: false
  management_interface: Management1/1
  p2p_uplinks_mtu: 9194
  platforms:
  - AWE-5310
  - AWE-7230R
- feature_support:
    bgp_update_wait_for_convergence: true
    bgp_update_wait_install: false
    interface_storm_control: false
    platform_sfe_interface_profile:
      max_rx_queues: 16
      supported: true
    queue_monitor_length_notify: false
  management_interface: Management1/1
  p2p_uplinks_mtu: 9194
  platforms:
  - AWE-5510
  - AWE-7250R
- feature_support:
    bgp_update_wait_for_convergence: true
    bgp_update_wait_install: false
    interface_storm_control: false
    poe: true
    queue_monitor_length_notify: false
  management_interface: Management1
  p2p_uplinks_mtu: 9194
  platforms:
  - AWE-7220R
```
