### DISCUSSION TITLE
add 'network 1.1.1.1/24' to vrf bgp ipv4

### DISCUSSION THREAD

**Discussion by PieterL75** [aristanetworks/avd#5328] [Q&A]
I want to add 'network' statements to my BGP vrf ipv4.
There is no design var for that, so I wanted to do that with structured config. but it acts unexpected.

I have
```
tenants:
 - name: tenant1
    vrfs:
    - name: vrf1
       bgp_peers:
         - ip_address: 1.2.3.4
            remote_as: 666
       structured_config:
          address_family_ipv4:
            networks:
              - prefix: 5.5.5.0/24
```
but that network statement ends up on the end of the structured config, and not under bgp/vrf/vrf1

**Comment by PieterL75** [comment]
Found it...
the structured_config had to be under the bgp: section

```
tenants:
 - name: tenant1
    vrfs:
    - name: vrf1
       bgp_peers:
         - ip_address: 1.2.3.4
            remote_as: 666
      bgp:
         structured_config:
            address_family_ipv4:
              networks:
                - prefix: 5.5.5.0/24
```
