### DISCUSSION TITLE
EVPN A/A How to use unique VTEP IP and not anycast one

### DISCUSSION THREAD

**Discussion by onurgashi** [aristanetworks/avd#705] [Q&A] [answered]
## Summary

In cases where A/A is implemented, we most likely will run unique ASN per leaf, and no peer-link between.
This pushes the config to:
- Use unique ASN per leaf
- Use unique IP for loopback as source for VXLAN

In such cases we should not define loopback1 as there is no common loopback needed, and live with loopback0 that can be used as source.

We should define a knob that by default is true, but can be false so it won't create loopback1 and will change vxlan source interface in case of A/A.

`vxlan_source_interface_lo1: false`

## Component Name

eos_designs.eos_l3ls_evpn

### Expected results

```shell
Vxlan1 to use Lo0 as source.
```

**Comment by lermilov** [comment]
Possible fix:
1. Within /base/fabric/interfaces/leaf-vtep-vxlan-tunnel-loopback.j2:
```
{# Leaf VTEP vxlan tunnel loopback source interface #}
{% if vxlan_source_interface_lo1 is defined and vxlan_source_interface_lo1 == true %}}
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
...
{% endif %}
```
2. Within base/tenant_evpn_vxlan/leaf_vxlan_vtep_interface:
```
{# vxlan-vtep interface #}
  Vxlan1:
    description: {{ inventory_hostname }}_VTEP
{% if vxlan_source_interface_lo1 is defined and vxlan_source_interface_lo1 == false %}
    source_interface: Loopback0
{% else %}
    source_interface: Loopback1
{% endif %}
...
```

3. Add `vxlan_source_interface_lo1: true` to eos_l3ls_evpn defaults variables

**Comment by onurgashi** [comment]
Solution @titom73 is really good actually, just doing `mlag: false`, we create unique IP per Leaf for Vxlan1.
I guess only drawback is the additional interface / IP block.

**Comment by titom73** [comment, marked as answer]
In case you don't want MLAG configured in a node group, you can configure `mlag: false` and then it will generate a Loopback1 IP per device and not shared across devices.

Inventory configuration:

```yaml
l3leaf:
    EAPI_LEAF3:
      bgp_as: 65103
      mlag: false
      filter:
        tenants: [ 'Tenant_A', 'Tenant_B' ]
        tags: [ 'POD03', 'DC1' ]
      nodes:
        EAPI-LEAF3A:
          id: 5
          mgmt_ip: 10.73.254.17/24
          mac_address: '0c:1d:c0:1d:62:01'
          spine_interfaces: [Ethernet7, Ethernet7]
        EAPI-LEAF4A:
          id: 6
          mgmt_ip: 10.73.254.18/24
          mac_address: '0c:1d:c0:1d:62:01'
          spine_interfaces: [Ethernet8, Ethernet8]
```

And then structured configuration reports 2 different Loopback1

__EAPI-LEAF3A__

```yaml
loopback_interfaces:
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 192.168.254.7/32
    isis_enable: EVPN_UNDERLAY
    isis_passive: true
```

__EAPI-LEAF4A__

```yaml
loopback_interfaces:
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 192.168.254.8/32
    isis_enable: EVPN_UNDERLAY
    isis_passive: true
```
